[package]
name = "kposter"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.15"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = { version = "1.41.1", features = ["full"] }
