[package]
name = "kposter"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = "1.0.0"
features = "0.10.0"
headless_chrome = "1.0.15"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde = "1.0.215"
tokio = { version = "1.41.1", features = ["full"] }
